#配置端口信息
server:
    port: 80
spring:
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true
    main:
        #启动不显示banner
        show_banner: false
    #数据源和数据连接池的配置
    datasource:
        name: test
        url: jdbc:mysql://192.168.110.112:3306/bxt_api
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #redis配置
    redis:
        port: 6379
        database: 0 # database name
        host: 192.168.110.112 #server host
        password: #server password
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
        timeout: 0
        #sentinel:
            #master: #Name of Redis server.
            #nodes: #Comma-separated list of host:port pairs.
    #视图指定类型和路径
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    data:
        #mongodb配置
        mongodb:
               host: 127.0.0.1
               port: 27017
               username: dba
               password: dba
               database: test
               #authenticationDatabase: test
#mybatis配置
mybatis:
    mapperLocations: classpath*:org/cc/*/*.xml
    typeAliasesPackage: org.cc
    basePackages: org.cc.dao
    #分页插件配置
    pagehelper:
        dialect: mysql
        offsetAsPageNum: false
        reasonable: true
        supportMethodsArguments: true
        returnPageInfo: check
        params: count=countSql
#指定log的配置文件
logging:
    config:logback.xml